### ISSUE TITLE
Migrate GitHub Actions Workflow to Use GITHUB_TOKEN for Container Registry Authentication

### ISSUE THREAD

**Issue by MiggiV2** [workaround-org/presentnow-backend#4]
After moving the repository from a personal account (`vvilip/presentnow-backend`) to the `workaround-org` organization, the existing GitHub Actions workflow is configured to use a `DOCKER_TOKEN` secret for authenticating with the GitHub Container Registry (`ghcr.io`). This setup is no longer valid, as the token is tied to the old personal account.  

**Goal:**  
Update the `.github/workflows/workflow.yml` file to use the `GITHUB_TOKEN` (GitHub's automatic token) for authenticating with the GitHub Container Registry. This will align the workflow with the new organization context and eliminate reliance on outdated secrets.  

---

### **Current Workflow Configuration**  
The existing `docker/login-action` step uses:  
```yaml
- name: Log in to GitHub Container Registry
  uses: docker/login-action@v3
  with:
    registry: ${{ env.REGISTRY }}
    username: vvilip
    password: ${{ secrets.DOCKER_TOKEN }}
```  
This configuration is tied to the old personal account (`vvilip`) and the `DOCKER_TOKEN` secret, which is no longer valid.  

---

### **Proposed Changes**  
Update the workflow to use the `GITHUB_TOKEN` (GitHub's built-in token) for authentication. This token is automatically available in all workflows and provides access to the organization's repositories and container registry.  

**Steps to Implement:**  
1. **Update the `IMAGE_NAME` environment variable** to reflect the new organization:  
   ```yaml
   env:
     REGISTRY: ghcr.io
     IMAGE_NAME: ghcr.io/workaround-org/presentnow-backend
   ```  

2. **Replace the `DOCKER_TOKEN` secret** with the `GITHUB_TOKEN` in the `docker/login-action` step:  
   ```yaml
   - name: Log in to GitHub Container Registry
     uses: docker/login-action@v3
     with:
       registry: ${{ env.REGISTRY }}
       username: workaround-org
       password: ${{ secrets.GITHUB_TOKEN }}
   ```  

   - **Username:** Use the organization name (`workaround-org`) as the username for the registry.  
   - **Password:** Use the `GITHUB_TOKEN` secret for authentication.  

---

### **Benefits of This Change**  
- **Simplifies secret management:** Removes reliance on the outdated `DOCKER_TOKEN` secret.  
- **Improves security:** The `GITHUB_TOKEN` is automatically scoped to the workflow and does not require long-term storage.  
- **Aligns with the new organization context:** Ensures the workflow is configured for the `workaround-org` organization.  

---

### **Verification**  
After applying these changes:  
1. Test the workflow by pushing a change to the `main` branch and observing the build and push process.  
2. Confirm that the Docker image is successfully pushed to `ghcr.io/workaround-org/presentnow-backend`.  

---

### **Documentation**  
Update any internal documentation or README files to reflect:  
- The new organization name (`workaround-org`).  
- The use of the `GITHUB_TOKEN` for container registry authentication.  

---

**Entities Involved:**  
- `.github/workflows/workflow.yml` (GitHub Actions workflow).  
- `ghcr.io` (GitHub Container Registry).  
- `workaround-org/presentnow-backend` (new organization and repository).  

**Additional Notes:**  
- The `GITHUB_TOKEN` is automatically scoped to the repository and workflow, so no additional permissions are required.  
- Ensure the organization has enabled container registry access for the repository if not already configured.
